<?php
class LAPIErrors {

	private static $errors = array(
	'100'=>'Expected before ref/trans ID = 0: wallet not previously loaded.',
	'101'=>'Wallet exhausted: retry after {0}.',
	'102'=>'Expected before ref/trans ID [{0}] but supplied [{1}]: wallet previously loaded.',
	'103'=>'Already returned one week of data: retry after {0}.',
	'105'=>'Invalid characterID.',
	'106'=>'Must provide userID parameter for authentication.',
	'107'=>'Invalid beforeRefID provided.',
	'108'=>'Invalid accountKey provided.',
	'109'=>'Invalid accountKey: must be in the range 1000 to 1006.',
	'110'=>'Invalid beforeTransID provided.',
	'111'=>'{0} is not a valid integer.',
	'112'=>'Version mismatch.',
	'113'=>'Version escalation is not allowed at this time.',
	'114'=>'Invalid itemID provided.',
	'115'=>'Assets already downloaded: retry after {0}.',
	'116'=>'Industry jobs already downloaded: retry after {0}.',
	'117'=>'Market orders already downloaded: retry after {0}.',
	'118'=>'Expected beforeKillID = 0: wallet not previously loaded.',
	'119'=>'Kills exhausted: retry after {0}.',
	'120'=>'Expected beforeKillID [{0}] but supplied [{1}]: kills previously loaded.',
	'121'=>'Invalid beforeKillID provided.',
	'122'=>'Invalid or missing list of names.',
	'123'=>'Invalid or missing list of IDs.',
	'124'=>'Character not enlisted in Factional Warfare.',
	'125'=>'Corporation not enlisted in Factional Warfare.',
	'126'=>'Invalid ID found in ID list. Please ensure input is a comma seperated list of valid 32-bit non-negative integers.',
	'127'=>'Please supply valid eventIDs.',
	'128'=>'IDs contained repeated instances of (at least) ID {0}. Please do not make redundant requests.',
	'129'=>'Input may not exceed {0} IDs.',
	'130'=>'All input must be valid ownerIDs or typeIDs.',
	'131'=>'Calendar Event List not populated with upcoming events. You cannot request any random eventID.',
	'132'=>'Calendar Event not found in upcoming events list. You cannot request any random eventID or CCP sponsored events.',
	'133'=>'Calendar Event List of attendees currently not accessible for this event.',
	'200'=>'Current security level not high enough.',
	'201'=>'Character does not belong to account.',
	'202'=>'API key authentication failure.',
	'203'=>'Authentication failure.',
	'204'=>'Authentication failure.',
	'205'=>'Authentication failure (final pass).',
	'206'=>'Character must have Accountant or Junior Accountant roles.',
	'207'=>'Not available for NPC corporations.',
	'208'=>'Character must have Accountant, Junior Accountant, or Trader roles.',
	'209'=>'Character must be a Director or CEO.',
	'210'=>'Authentication failure.',
	'211'=>'Login denied by account status.',
	'212'=>'Authentication failure (final pass).',
	'213'=>'Character must have Factory Manager role.',
	'501'=>'GetID({0}) is invalid or not loaded.',
	'503'=>'GetSkillpointsForLevel({0}, {1}): invalid input.',
	'504'=>'GetRace({0}): invalid race.',
	'505'=>'GetGender({0}): invalid gender.',
	'506'=>'GetBloodline({0}): invalid bloodline.',
	'507'=>'GetAttributeName({0}): invalid attribute.',
	'508'=>'GetRefType({0}): invalid reftype.',
	'509'=>'attributeID {0} has null data components.',
	'510'=>'Character does not appear to have a corporation. Not loaded?',
	'511'=>'AccountCanQuery({0}): invalid accountKey.',
	'512'=>'Invalid charID passed to CharData.GetCharacter().',
	'513'=>'Failed to get character roles in corporation.',
	'514'=>'Invalid corpID passed to CorpData.GetCorporation().',
	'516'=>'Failed getting user information.',
	'517'=>'CSV header/row count mismatch.',
	'518'=>'Unable to get current TQ time.',
	'519'=>'Failed getting starbase detail information.',
	'520'=>'Unexpected failure accessing database.',
	'521'=>'Invalid username and/or password passed to UserData.LoginWebUser().',
	'522'=>'Failed getting character information.',
	'523'=>'Failed getting corporation information.',
	'901'=>'Web site database temporarily disabled.',
	'902'=>'EVE backend database temporarily disabled.',
	'903'=>'Rate limited [{0}]: please obey all cachedUntil timers.',
	'904'=>'Your IP address has been temporarily blocked because it is causing too many errors. See the cacheUntil timestamp for when it will be opened again. IPs that continually cause a lot of errors in the API will be permanently banned, please take measures to minimize problematic API calls from your application.',
	'999'=>'User forced test error condition.');

	public function get($code) {
		return self::$errors[$code];
	}
}
?>